server:
  port: 8081

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "org.example.dto"
        spring.json.value.default.type: "org.example.dto.NotificationMessageDto"
        spring.json.use.type.headers: false

  mail:
    host: mailhog
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
    ipAddress: 127.0.0.1
    prefer-ip-address: true
    nonSecurePort: ${server.port}
    statusPageUrlPath: /actuator/health
    healthCheckUrlPath: /actuator/health

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - env
  endpoint:
    health:
      show-details: always
